#!/bin/bash
#Colin O'Neal
#CSC460
#/home/oneal_wc/csc460/grading/peanut/peanut
#Peanut project

echo "Running program..."
cmd='no'
args='no'
#does the program until nutsout is called
while(test "$cmd" != "nutsout")
do
	echo -n "Peanut> "									##prints Peanuts on every command line 
	read cmd args										#Reads in the user input

	if(test $cmd == "nutsout") then								#Does the nutsout program
		cmd="nutsout"

	elif(test $cmd == "helpnuts") then							#Does this when helpnuts is entered
		echo "showcase "filename" " "nutcall "userid" " "nutlist " "nutstuff " "helpnuts "  ##Prints out list of all commands peanut has
		echo "nutty " "peanutbutter filename " "snoopy "args" " "nutsout"

	elif(test $cmd == "nutlist") then							#Does this when nutlist is entered 
		name=`who | cut -d" " -f1`	
		for x in $name
		do
			list=`grep $x /etc/passwd | cut -d":" -f5 | cut -d"," -f1`
			echo $list								##Prints out the list of names of the people that are logged on
		done

	elif(test $cmd == "nutstuff") then							#Does this when nutstuff is entered
		directory=`ls`									#Shows the current directory
		for x in $directory
		do
			echo $x
		done

	elif(test $cmd == "bignut") then							#Secret program that goes into another bash
		bash

	elif(test $cmd == "nutty") then								#Does this when nutty is entered
		useron=`who | cut -d" " -f1`
		for x in $useron
		do
			list=`grep $x /etc/passwd | cut -d":" -f5 | cut -d"," -f1`
                        echo -e All work and no play makes $list a dull boy
		done
		sleep 4
		echo -n Deleting All Files...
		sleep 1
		echo -n 3
		sleep 1
		echo -n " " 2
		sleep 1
		echo -n " " 1
		sleep 2
		clear
		echo  " " Just Kidding, Continue with the peanut				##Does some random nutty stuff

	elif(test $cmd == "nutcall") then							#Does this when nutcall and some userid is entered
		userid=$args
		for x in $userid
		do
			user=`grep $x /etc/passwd | cut -d":" -f5 | cut -d"," -f1`
			phone=`grep $x /etc/passwd | cut -d"," -f4 | cut -d":" -f1`
			echo -e $user "\t" $phone
		done										#Prints out the name and phone# of the userid entered

	elif(test $cmd == "showcase") then							#Does this when showcase and some filename is entered
		file=$args
		less $file									#Shows the filename entered and able to scroll down through it

	elif(test $cmd == "peanutbutter") then							#Does this if peanutbutter and some filename is entered
		file=$args
		vi $file									#Goes into editor mode for file entered

	elif(test $cmd == "snoopy") then							#Does the snoopy code when snoopy is entered
		./snoopy $args
		
	else											#When false command is entered this will print and let you try again
		echo "Not a valid command"
	fi
done
echo "All Done"											##After nutsout is entered this prints out letting you know your done
